const wordList = [
    "abeja", "aguila", "alce", "alpaca", "anaconda", "anguilla", "avestruz", "ardilla", "avispa", "antilope",
    "ballena", "bufalo", "buho", "burro", "buitre",
    "caballo", "cabra", "camello", "cangrejo", "caracol", "chancho", "cuervo", "cocodrillo", "cebra",
    "delfin", "elefante", "escarabajo", "escorpion", "erizo",
    "foca", "gallina", "gato", "gaviota", "gorila",
    "hiena", "hipopotamo", "hormiga", "huron", "hiena",
    "iguana", "jaguar", "jirafa",
    "koala", "leon", "lobo", "loro", "leopardo", "langosta",
    "mono", "murcielago", "mariposa", "morsa", "medusa",
    "nutria", "narval", "ñandu", "orangutan", "ocelote",
    "oso", "ornitorrinco", "ocelote",
    "panda", "pinguino", "pulpo", "pato", "perezoso", "perro",
    "rinoceronte", "rana", "raton",
    "serpiente", "tigre", "tortuga", "tiburon", "tucan", "toro",
    "unicornio", "urraca",
    "vaca", "venado", "vibora",
    "yacare", "yaguarete",
    "zarigüeya", "zorro",
  ];